---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-email
  namespace: tripplanner
spec:
  encryptedData:
    smtp-password: AgBCZFjMpS7RSvMnYKj5A2XvEO+UA1HD/beTgVqHqfFTRGlOiKNbFmWOJFOvnRh1Wm0RUOZCc9ckyusec+2ELlkVIAqmOJ/N2x3r+JDL7MROcYYb6WliCzhbps8+qJsO61xcAZVuS+AGFym7W5f8sY91vUJB0qHWDnpU4I1V28QFTH5MIlrTW6PYGFoeGES1Ss0dD4eJHnC/8/bheRo8t4DrneQl3l4jUOupQ896BhmkUdW2T7jtxPL/dRp2ZqZ1FZzk1/bDzX2T68DHoW86+4o/idwVeChzeJGB6An6YcHdqIk8f8FvCyIKjc1QSjdXClLUVa+qFMeb3ELW7hUEkRGQe23mV/kZWLKrwU7ydXnBm75w24+Rl85O1PYGwT9H4r5FNKx3vspFre+Rb+6DYAp/hBZUNzGIyl+zA1LpMeAgM0qzAB1umcoLRCQOwHNzu5JwwTqJS0jMpHjrJm0a97f4GdjTLZnPSVQmPwgvy1wgZpQrXktB+Mg4cZBx9usG5Qauo0pqutE5uUOBLdUeILIhBiQn0lpZdVByczJ+5UQpkwyj+VEOOteGJ+oj6TjnNr4K759XpaYLedqCZQ8KMxZ1oIGC3Z+/kwKI4lEzB88+ULI3XLXzQGjctwcOsLcA2okHgtuYUedWCZI3/nKdFzgfrD4sVzaa1PiCxtqj8Ps77afGmaD68R9y8hop8c2wz9SZeRhl6qRQ9oN7vT+KDbwh
  template:
    metadata:
      name: alertmanager-email
      namespace: tripplanner
