apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager-email-sealed-secret.yaml
  - alertmanager-config.yaml
  - auth-service-monitor.yaml
  - grafana-dashboard.yaml
  - prometheus-rules.yaml
  - trip-service-monitor.yaml
