apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trip-service
  labels:
    app.kubernetes.io/name: trip-service
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: tripplanner
    release: monitoring
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - tripplanner
  selector:
    matchLabels:
      app.kubernetes.io/name: trip-service
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: tripplanner
  endpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s

