apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: tripplanner
automountServiceAccountToken: false

