apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-service-config
  labels:
    app.kubernetes.io/name: trip-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: tripplanner
data:
  NODE_ENV: production
  PORT: "5002"
  REDIS_URL: redis://redis:6379
