apiVersion: v1
kind: ServiceAccount
metadata:
  name: trip-service
  labels:
    app.kubernetes.io/name: trip-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: tripplanner
automountServiceAccountToken: false
