apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tripplanner

resources:
  - namespace.yaml
  - redis
  - auth-service
  - trip-service
  - frontend
  - network-policies.yaml

images:
  - name: docker.io/ptuyennn/tripplanner-frontend
    newTag: 18b59e153ba0
  - name: docker.io/ptuyennn/tripplanner-auth
    newTag: 18b59e153ba0
  - name: docker.io/ptuyennn/tripplanner-trips
    newTag: 18b59e153ba0
